version: '3.8'
services:
  dev-database:
    image: postgres:16.1
    container_name: dev-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - nestjs-network
  app:
    image: node:20.11.1
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./:/app
    command:
      - 'sh'
      - '-c'
      - 'yarn && sleep 2 && yarn start'
    ports:
      - 5000:5000
    networks:
      - nestjs-network
networks:
  nestjs-network:
# -d: run in background

# docker compose up -d

#### turn off ####
# docker compose down

# run only dev-database
# docker compose up -d dev-database -d

#remove container + volume
# docker compose rm dev-database --stop --force --volumes
