version: '3.8'
services:
  dev-database:
    image: postgres:16.1
    container_name: dev-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    networks:
      - nestjs-network
  app:
    image: node:20.11.1
    container_name: nestjs-app
    command: yarn start
    ports:
      - 5000:5000
networks:
  nestjs-network:
# -d: run in background

# docker compose up -d

#### turn off ####
# docker compose down

# run only dev-database
# docker compose up -d dev-database -d

#remove container + volume
# docker compose rm dev-database --stop --force --volumes
