version: '3.8'
services:
  dev-database:
    image: postgres:16.1
    container_name: dev-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    networks:
      - nestjs-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    image: node:20.11.1
    working_dir: /app
    volumes:
      - ./:/app
    container_name: nestjs-app
    ports:
      - 5000:5000
    depends_on:
      - dev-database
    user: 'node'
    # command: bash -c "npm install && npx prisma migrate dev && npm run prisma generate && npm run prisma deploy && npm run dev"
    command: bash -c "npm install && npm run dev"
networks:
  nestjs-network:
# -d: run in background

# docker compose up -d

#### turn off ####
# docker compose down

# run only dev-database
# docker compose up -d dev-database -d

#remove container + volume
# docker compose rm dev-database --stop --force --volumes
